=== Running ModelMaker standalone

This assumes you have downloaded `3w.zip`.
// NOTE: 3w.zip must contain (1) .3w/tw-dep.jar, (2) ModelMaker.jar, (3) UserCodeRunner.java

. Unzip `3w.zip` in your user home directory (important), keeping the internal directory tree. This will extract a file `modelMaker.jar` and a `.3w` directory containing more jar files.
. Double-click on `modelMaker.jar`. This should launch the ModelMaker application.
. If this does not work, open a terminal and type `java -jar modelMaker.jar`. This should launch the ModelMaker application.

WARNING: This way of launching 3Worlds is sensitive to the relative location of `modelMaker.jar` and the other jars that are in the `.3w` directory, ie `modelMaker.jar` *must* be exactly one directory above `.3w`.

To remove this constraint, you can bypass `modelMaker.jar` by directly launching it from the jars contained in `.3w`:
[source,bash]
----
java -cp .3w/tw-dep.jar au.edu.anu.twuifx.mm.Main
----

The last is the preferred method as any errors that may arise will appear in the terminal window.
// I think we could supply a bash shell and a windows .bat file to handle this - Ian

NOTE: to develop your model-specific code, you will need to setup a java development environment as shown in section <<truesetting-up-a-java-development-environment-for-the-user-code,Setting up Java>>. 