=== Elaborating the model structure: Testing the Intermediate Disturbance Hypothesis

==== Introduction

In this tutorial we add a disturbance to effect the community of plants modelled with the competitive Lotka-Volterra equation (CLV) used in Tutorial 3. This will provide a tool to examine the Intermediate Disturbance Hypothesis (IDH). 

In the tutorial following this, we will modify these specifications to make a cleaner design.

==== Specifications

Begin this tutorial using the Lotka-Volterra specifications from the `Tutorials` menu as a starting point.

. Create a new project from on `Tutorials -> 4 LotkaVolterra` and name it "Tut4".

===== Data definitions

. Collapse all nodes except for the `dataDefinition` sub-tree, hide the _cross-links_ ('*X*' button), and re-apply the layout ('*L*' button).

. Add a new `record` to  `dataDefinition:dDef` and name it "dec".

Data is divided into three classes in _3Worlds archetype_: constants (cst), drivers (drv) and decorators (dec). Decorators are values derived from the current value of the drivers. In this tutorial we will output a species diversity index (Shannon's), derived from relative abundance of each species. 

As noted previously, these names are just for clarity - they don't impose a role. You can name a record any thing you like. The role is defined when these records are later collected together within a `category` (cf ).

. Add a `field` to `record:dec`, name it "div" (diversity index) of type `Double`.

The disturbance model is simply one with a frequency and severity.

. Add a new `record` to `dataDefinition:dDef` and name it "distCst" (disturbance constants).

. Add two fields to this record, both of type `Double` called "freq" and "severity" respectively. 

The previously defined records could now be named more appropriately. A trick with the layout functions is that they order the trees alphbetically. To arrange things so related nodes of a particular role are close together, prefix the name with the same string - in this case "dist". We could name all the data associated with the CLV with "comm" (community).

. Rename `record:cst` to `record:commCst`, `record:drv` to `record:commDrv` and `record:dec` to `record:commDec`.

. Re-apply the layout. The data fields should now be in a more sensible arrangement.

Fill out the meta-data properties with at least the desciption of the data. As mentioned, these descpritons become part of the comments in the generated Java code so the file can be largely self-documenting.

Add the following descriptions to the new data defintions:

- `freq#description`: "average return time"
- `severity#description:`"% population decrease"
- `div#description:` "shannon diversity"

That's all the data need for this model and now we can attend to process and then structure. The task list is empty at this stage.

===== Process






==== Next

