===== The representation of time

Simulation is about mimicking the dynamics of a real system. Here, dynamics is specified by attaching particular behaviours (called <<trueprocess,processes>>) to either  <<configuration-ecosystem-structure.adoc#truecategory,categories>> or <<configuration-ecosystem-structure.adoc#truerelationtype,relation types>>. Processes may act at a different rhythm or rate in nature, so we need to have a great flexibility in the way time is represented.

====== Time line

`/3worlds/system/dynamics/*timeLine*:<[underline]##__name__##>` {1}

Every simulator has a reference _time line_. Since different ecological processes may run according to different time models, they must refer to a common time frame for interaction to be possible among them. A `*timeLine*` defines what kind of time scale and time units can be used in a simulation. In 3Worlds, time is always discrete in the end, so that the selected values of time scale and time unit define the time _grain_ of the simulation, i.e. the duration below which events are considered simultaneous. Internally, the `ModelRunner` uses integers to represent time, with 1 = one time grain.

include::ArchetypeDoc-timeLine.adoc[]

====== Timers

`/3worlds/system/dynamics/timeLine/*timer*:<[underline]##__name__##>` {1..*}

Ecological processes may be run following different times. A timer is a particular way of representing time in the simulator. Timers may differ in parameters, like e.g. two timers using different time steps; but they can also be radically different in their logic: e.g. clock-like ticking vs. event-driven simulation.

.How do timers work?
[#timer-howto]
****
Internally, each timer is an instance of the class `Timer`, which is able to return the next time where computation must be made according to its own logic. Every iteration of 3Worlds starts with the simulator asking all timers for their next time, then keeping all of those with the next time closest to last time, and executing them __in unpredictable order__. 3Worlds uses long integers to measure time internally, which means that simultaneous events are possible (times may be strictly equal). The finest time interval is given by `TimeLine.shortestTimeUnit`.
****

// now deprecated - because only valid for clock timer
// include::ArchetypeDoc-timer.adoc[]

_Properties for_ `timer`:

[horizontal]
`subclass`:: the type of `timer` to use.
+
****
_possible values_:

[horizontal]
`ClockTimer`:: Time is incremented by a constant amount _dt_. This is commonly used to simulate regular processes like growth.
`EventTimer`:: Model dynamics generates _events_ and computes the date in the future at which they are going to occur. This is commonly used to generate irregular processes like fire occurrence.
`ScenarioTimer`:: *Not yet implemented*.
****

_Additional properties when_ `class = ClockTimer`

[horizontal]
`timeUnit`:: the base time unit used by this timer. _cf._ `timeLine.shortestTimeUnit` for the valid values of this property

`nTimeUnits`:: the number of base time units in the time unit of this model (__e.g.__, a model may have a 2 year time unit)

`dt`:: The constant time increment used in this `ClockTimer`, expressed as an integer number of `timer` base unit (=`timer.nTimeUnits` × `timer.timeUnit`). For example, if the `timer` has `timeUnit` = `DAY` and `nTimeUnits` = 3, `dt` is expressed in units of 3 days (e.g. `dt` = 2 means the time increment is 6 days).
+
WARNING: if calendar time is used (`timeLine.scale` = `GREGORIAN`), then `dt` will sometimes not be constant (e.g. if `dt` = 2 `MONTH`, `dt` will vary in duration between 59 and 62 days according to the exact date).

`offset`:: In some cases it is desirable to offset a `ClockTimer` relative to another one running at the same time step, for example to be certain of their order of execution or to simulate cyclic phenomena (e.g. seasons). The timer will start after `offset` × `timeUnit` units, where `offset` is a fraction between 0.0 and 1.0.

_Additional cross-links when_ `class = EventTimer`

An `EventTimer` maintains a queue of time events that gets populated by user-defined ecological <<truefunction,functions>>. This way, future events depend on the dynamics of the system. Functions that can populate an event queue will have an `EventQueue` argument in their heading, usable to create future time events. Events must set a time in the future, i.e. their time must be larger than current time. Event times are always expressed in ``Timeline.shortestTimeUnit``s in an `EventTimer`.

`fedBy -> initFunction:<[underline]##__name__##>` {1}::
This link is used to set the first event of an `EventTimer` at simulation start, hence from an <<configuration-ecosystem-structure.adoc#truesetting-decriptor-values,`initFunction`>>. Without this initial event, the timer will never start. More than one event can be created here.

`fedBy -> function:<[underline]##__name__##>` {0..*}::
These links indicate which functions can populate the event queue with time events. Multiple events can be created here.

====== Simulation stopping condition

`/3worlds/system/dynamics/*stoppingCondition*:<[underline]##__name__##>` {0..*}

A simulation may be run indefinitely (interactively), but in big simulation experiment it is useful to automatically stop the simulations according to some criterion. Besides the simplest stopping condition, reaching a maximal time value, 3Worlds provides many other possibilities to stop a simulation (e.g. based on a population size, on a variable passing a threshold value, etc.).

When no stopping condition is defined, the simulation will run indefinitely.

_Properties for_ `stoppingCondition`

[horizontal]
`subclass`:: The type of stopping condition to use
+
****
_possible values_:

`SimpleStoppingCondition`:: 
Simulation stops when a maximal time value is reached.
`ValueStoppingCondition`:: 
Simulation stops when a variable in a reference system component reaches a given value.
`InRangeStoppingCondition`:: 
Simulation stops when a variable in a reference system gets within the given range.
`OutRangeStoppingCondition`:: 
Simulation stops when a variable in a reference system gets out of the given range.
`MultipleOrStoppingCondition`:: 
Compound stopping condition: simulation stops when _any_ of the elementary stopping conditions within this multiple condition's list is true.
`MultipleAndStoppingCondition`:: 
Compound stopping condition: simulation stops when _all_ of the elementary stopping conditions within this multiple condition's list are true.
****

_Additional properties when_ `class = SimpleStoppingCondition`

[horizontal]
`duration`:: The duration of the simulation beyond time line `timeOrigin`, in time line `shortestTimeUnits`.

_Additional cross-links when_ `class = ValueStoppingCondition`, `InRangeStoppingCondition`,  `OutRangeStoppingCondition`

`stopSystem -> component:<[underline]##__name__##>` {1}::
The system component in which some variable will be checked to stop the simulation.

_Additional properties when_ `class = ValueStoppingCondition`, `InRangeStoppingCondition`,  `OutRangeStoppingCondition`

[horizontal]
`stopVariable`:: The name of the variable in `stopSystem` which values are used to decide to stop the simulation.

_Additional properties when_ `class = ValueStoppingCondition`

[horizontal]
`stopValue`:: The value of `stopVariable` at which to stop the simulation.

_Additional properties when_ `class = InRangeStoppingCondition`, `OutRangeStoppingCondition`

[horizontal]
`upper`:: The upper value of the `stopVariable` range. Only `double` values are accepted.
`lower`:: The lower value of the `stopVariable` range. Only `double` values are accepted.

_Additional cross-links when_ `class = MultipleOrStoppingCondition`, `MultipleAndStoppingCondition`

`condition -> stoppingCondition:<[underline]##__name__##>` {1}::
These links point to the stopping conditions that will be used as elementary stopping conditions by the multiple and/or stopping condition. Use these links to construct complex stopping conditions.

===== The transformations of a system component

Changes in a _system component_ through time may be of different kinds: changes in __state__, i.e. in its driver and decorator variables; or more radical changes where the component actually changes __category__, so becomes represented by a different set of variables. Plus, a component may have an ephemeral life (lifespan property), which means component objects are dynamically created or deleted during a simulation.

====== Process

`/3worlds/system/dynamics/timeLine/timer/*process*:<[underline]##__name__##>` {1..*}

_Processes_ are used in 3Worlds to compute change in <<configuration-ecosystem-structure.adoc#truesystem-component,_system components_>>. Each process acts on system components of a particular group of <<purpose.adoc#truecategories,categories>> and is scheduled by a particular <<truetimers,timer>>. Processes contain user-defined code that represents ecological processes. This gives 3Worlds its versatility: one can mix in a single model completely different ecological entities (system components of different categories), implement any ecological process depending on user needs, and put them to work on different time scales (times). A `process` is run according to its parent `timer`.

_Cross-links for_ `process`

A process can act on a single system component at a time (called the _focal_ system component), or on a pair of components linked by a relation (called the _focal_ and the _other_ system components). This is specified using the `appliesTo` cross-link (one at least must be present):

`appliesTo -> category:<[underline]##__name__##>` {0..*}::
These links indicate the categories of system components that will be acted on by the process. 
`appliesTo -> relation:<[underline]##__name__##>` {0..1}::
This link indicates to which relation type between system component the process applies.

IMPORTANT: A process *must* apply either to categories (__category process__) or to a single relation type (__relation process__), but cannot apply to both.

`dependsOn -> process:<[underline]##__name__##>` {0..*}::
This link tells that the process must be activated _after_ the processes targeted by the links. Use this link to organize computations when there are dependencies between them.
`inSpace -> space:<[underline]##__name__##>` {0..1}::
This link indicates that this process will make use of this  <<configuration-ecosystem-structure.adoc#truethe-representation-of-space,space>> for its optimisation of neighbour searches. Use this link when you want fast search for candidates to establish a relation, i.e. in association with the `relateToDecision` function. The required property `searchRadius` in the `inSpace` link tells to which _maximal_ distance candidates for establishing a relation must be searched. 3Worlds will only present components at a shorter distance than `searchRadius` (possibly none) to the `relateToDecision` function. A value of zero means the algorithm searches for the closest neighbour only (possibly more than one if all exactly at the same distance), whatever its distance to the focal component.

// NB it may make sense to have a different property for handling the number of neighbours to search for, ie 1 returns the closest neighbour, 2 the 2 closest, etc.

WARNING: Forgetting to set the value of `searchRadius` is a common source of unexpected behaviour in spatial models.

.How do processes work?
[#process-howto]
****
Internally, an instance of the `Process` class implements a '__for each__' loop on system components during an iteration step, as scheduled by its `Timer`. The order in which the components are processed in a loop is unpredictable (not fixed, nor random); the only safe assumption is to consider that they are all processed simultaneously.

If the process applies to a list of categories, it is a single loop on all components belonging to these categories. This is the `ComponentProcess` sub-class.

If it applies to a relation type, it is either (1) a double loop, possibly optimized by using a space, on components belonging to the 'from' list of categories of the relation type, and components belonging to the 'to' list of categories of the relation type (`SearchProcess` sub-class); or (2) a single loop on relations instances of its relation type (`RelationProcess` sub-class).

Processes of a same timer are run in any (= unpredictable) order unless explicitly ordered by the use of the `dependsOn` cross-link. Ordering processes in such ways defines _causal steps_ (<<truecausality>>) within the time steps.

In short: process = (parallel) loop on components (within one causal step) within one time step.
****

====== Function

`/3worlds/system/dynamics/timeLine/timer/*function*:<[underline]##__name__##>` {1..*}

This node is used to specify the details of the computations made in a `process`. The `process` defines which system components are going to be activated and at what time in the simulation course; the `function` defines which computations, in detail, will be applied to the system components of that process. This enables to build complex computations applying to one component (a series of ``function``s within a `process`) in the context of a particular subset of components (`process`).

There are different types of functions, differing by the way they affect system components and relations. The selection of a function type will trigger the generation in the model java source file of a method having the name specified in the `function` node name. This method is expected to be edited by the modeller in order to implement her/his favourite version of the ecological process modelled by the function. 

//todo: remove this condition !

CAUTION: The name of a function must be a valid java class name, starting with an uppercase letter.

include::ArchetypeDoc-function.adoc[]

IMPORTANT: The `relateToDecision` function has a special status among relation processes as it is used to establish a relation, whereas all other functions for relation processes use an already established relation. As a result, a process parent to a `relateToDecision` function cannot be parent to any other type of function. For computation efficiency, it is recommended to associate a <<configuration-ecosystem-structure.adoc#truethe-representation-of-space,_space_>> to the process parent to a `relateToDecision` function.

[horizontal]
`functionSnippet`:: This optional property is used in 3Worlds tutorial and test models  to store the java code of user-defined function. This code is inserted in the body of the generated user-code methods.

CAUTION: We recommend not to use snippets, or only for simple models, since it may cause problems when the code contained in a snippet contains compile errors, something very easy to achieve when, e.g., renaming a field or table. If you use it, do it with caution.


_Cross-links for_ `function`:

`useRNG -> rng:<__name__>` {0..1}::
Points to the <<configuration-dataDefinition.adoc#truerandom-number-channels,random number generator channel>> to use in this function. If unset, the default random number channel is used.

_Additional properties when_ `function = createOtherDecision`:

[horizontal]
`relateToProduct`:: A logical value (`false` by default) which tells to establish a permanent `parentTo` relation (defined in the `predefined` sub-tree: <<configuration-reference.adoc#truethe-predefined-sub-tree>>) between a parent component and its offspring created by calling `createOtherDecision`.

.How do functions work?
[#function-howto]
****
Functions are called within the loop on components of their parent process. The processing order of functions within their process is constant:

* In a `ComponentProcess`:
** execute all `changeState` functions
** then, all `deleteDecision` functions,
** then, all `createOtherDecision` functions,
** then, all `changeCategoryDecision` functions,
** then send data to all <<truedata-tracking,data trackers>>
* In a `SearchProcess`:
** execute all `relateToDecision` functions
* In a `RelationProcess`
** execute all `changeOtherState` functions
** then, all `maintainRelationDecision` functions,
** then, all `changeRelationState` functions

The order of these computations does not matter for _driver_ descriptors, nor for component creation and deletion, because all the changes are postponed until after the process loop is over. For example, a component may in the same time step reproduce an die. The order may only matter for __decorators__, which are provided here as a convenience for complex computations.

A way to make your model code efficient is to group functions run with the same timer in a single process, so that they are called in a single pass on components instead of many in case you use different processes. This assumes that your functions can be processed in any order without consequences on the outcome - which is not always true. If you need a precise ordering of function calls because, e.g. one of them requires that a decorator variable has been set by another, then you must place your functions in different processes linked by a `dependsOn` cross-link to tell which is computed first.

At the end of a process loop (causal step, <<truecausality>>):

* the values of all _drivers_ are updated (i.e. values computed by functions are stored in a _next_ driver data structure, which now replaces the _current_ driver structure);
* _components_ to be deleted and to be created as decided by `-Decision` functions, and _ephemeral_ relations to create/delete, are now inserted in the current list of components;
* _spaces_ are updated according to changes in the component community;
* _permanent_ relations between components are updated.


At the end of all process loops (time step, <<truecausality>>):

* all _decorators_ are set to zero;
* _automatic_ descriptors (e.g. component age, population numbers) are updated;
****

====== Function consequences

`/3worlds/.../process/function/*consequence*:<[underline]##__name__##>` {0..*}

Some functions may imply consequences: for example, a decision to delete another system component may be followed by a change in state based on the deleting component's state at the time it is deleted. Such functions that are only activated when certain events take place are called _consequences_ and may be specified by a child node to a function. Here also, rules apply:

[width="100%",options="header",cols="1,1,2"]
|====================
| function | consequence  |  use to
| `changeState` |  |  
| `changeRelationState` | |
| `changeOtherState` |  |
| `deleteDecision` | `changeOtherState` |  carry over values to another component linked by a `returnsTo` relation
| `createOtherDecision` | `setOtherInitialState` |  set the initial state of the new component
|  `relateToDecision` |  |
| `changeCategoryDecision` | `setOtherInitialState` |  carry over and compute values from the former component (__focal__) to the new recruit
| `maintainRelationDecision` |  |  
| `relateToDecision` |  |  
|====================

Consequence functions have the same properties and cross-links as functions (cf. above).

.How do consequence functions work?
[#consequence-howto]
****
Internally, consequence functions are just functions which are called _immediately after_ their parent function. E.g., in a `ComponentProcess` loop on `deleteDecision` functions, each `deleteDecision` function is immediately followed by a call to its consequence `changeOtherState` function, if any.
****

===== Data tracking

`/3worlds/.../process/*dataTracker*:<__name__>` {0..*}

Data trackers are used to get output from a simulation. This output can then be redirected either to graphic windows of `ModelRunner` or to a data file for later processing with other software. Using a data tracker is similar to what happens in the real world: you set a sensor into the system you want to monitor and wire it to a data logger which translates the signal into human-readable data. There are different kinds of data trackers according to the output format and the sampling method you want to use; and different ways of wiring these trackers to the simulated system and its components.

A data tracker will record values of descriptors (except constants) of a sample of system components or groups, or of the system itself and send them to any listener (usually a <<configuration-gui.adoc#truewidgets,widget>>) linked to it. The frequency of data sending is determined by the _timer_ of the parent _process_ of the data tracker.

IMPORTANT: A `dataTracker` node can only be specified in a _category process_, not in a __relation process__.

include::ArchetypeDoc-dataTracker.adoc[]

`subclass`:: The type of data tracker to use
+
****
_possible values_:

`DataTracker0D`:: time series tracker; returns (__t__, __x~1~__, ..., __x~n~__) values (where _t_ is time and _x~i~_ the descriptors of interest).
`DataTrackerXY`:: raw tracker; returns (__x__,__y__) values at each time step.
`DataTracker2D`:: *unimplemented yet*
****

_Cross-links for_ `dataTracker`

`sampleComponent -> componentType:<[underline]##__name__##>` {0..1}::
The `dataTracker` will track components of the `componentType` pointed by this link, following the sampling strategy specified by properties `samplingMode`, `sampleSize`, `statistics` and `tableStatistics`. _Permanent_ components will be tracked until the end of the simulation. _Ephemeral_ components are tracked all their life long: a new sampling is done every time a formerly tracked component is deleted. Sampling strategy can further be refined using two optional properties (see below).

+
IMPORTANT: The `componentType` categories must match those of the `process` parent of the `dataTracker`.

+
_Optional properties for_ `sampleComponent` __cross-links__:
+
[horizontal]
`idLifeCycle`::: The identifier of the _life cycle_ which components are to be sampled from, as a ``String``; only required if a life cycle has been specified. 
`idGroup`::: The identifier of the _group_ which components are to be sampled from,  as a ``String``; only required if a group has been specified

`sampleGroup -> groupType:<[underline]##__name__##>` {0..1}::
The `dataTracker` will track groups of the `groupType` pointed by this link. 

+
IMPORTANT: The `groupType` categories must match those of the `process` parent of the `dataTracker`.

+
_Optional property for_ `sampleGroup` __cross-links__:
+
[horizontal]
`idGroup`::: The list of identifiers of the groups to track, as a `StringTable`. If not set, all groups of the `groupType` are tracked.

`sampleLifeCycle -> lifeCycleType:<[underline]##__name__##>` {0..1}::
The `dataTracker` will track life cycles of the `lifeCycleType` pointed by this link.  

+
IMPORTANT: The `lifeCycleType` categories must match those of the `process` parent of the `dataTracker`.

+
_Optional property for_ `sampleLifeCycle` __cross-links__:
+
[horizontal]
`idLifeCycle`::: The list of identifiers of the life cycles to track, as a `StringTable`. If not set, all life cycles of the `lifeCycleType` are tracked.


`sampleArena -> system:<[underline]##__name__##>` {0..1}::
The `dataTracker` will only track the _system_ data.

`trackField -> field:<[underline]##__name__##>` {0..*}::
The `dataTracker` will track all fields pointed by these cross-links in all objects (__components__, __groups__, __life cycles__ or __system__) it is sampling.

`trackTable -> table:<[underline]##__name__##>` {0..*}::
The `dataTracker` will track all tables pointed by these cross-links in all objects (__components__, __groups__, __life cycles__ or __system__) it is sampling.

IMPORTANT: the trackField or trackTable cross-links must refer to fields or tables present in the categories of the parent `process` of the `dataTracker` (`process` `appliesTo` cross-links).

_Properties for_ `trackField` _and_ `trackTable` __cross-links__:

[horizontal]
`index`:: A list of ``String``s giving the range of table indices to track. The following rules are used to specify which cells of the table should be picked:
+
. an index specification for a table is enclosed in square brackets: `[]`;
. vertical bars separate dimensions: e.g. `[||]` refers to a table with three dimensions;
. a single number is used to specify a single cell in one dimension: e.g. `[1||]` refers to the cell 1 in dimension 1 (Note: this is the _second_ cell in this dimension as all dimension indices start at 0 = first cell);
. a list of cells in one dimension is specified using commas: e.g. `[1|0,2,7|]` refers to the cells 0, 2 and 7 in the second dimension;
. a range of cells in one dimension is specified using a column: e.g. `[1|0,2,7|2:4]` refers to the cells 2,3 and 4 in the third dimension;
. a negative number means that all cells in a dimension must be tracked _except_ this number: e.g. `[-1|0,2,7|2:4]` indicates that all cells in the first dimension except cell 1 must be tracked.
. a minus sign in front of a range means that all cells in a dimension must be tracked _except_ this whole range: e.g. `[1|0,2,7|-2:4]` indicates that all cells in the third dimension except cells 2, 3 and 4 must be tracked.
. an empty dimension means all cells in this dimension are to be tracked: e.g. `[1||2:4]` indicates that all cells in the second dimension will be tracked;
. an empty index string `[]`, or no index string, means that the whole table (all cells) is to be tracked.

+
The descriptors may be elaborate <<configuration-dataDefinition.adoc#truethe-descriptor-tree,hierarchical data structure>> which include a table at some level. For each table in this hierarchy, an index `String` as described above must be given in the index property, in a comma-separated list, e.g.: [0:2|0],[4,6] means that index [0:2|0] should be used for the top-level table of the descriptor, and index [4,6] for the bottom-level table.

*[TO DO: a few examples]*
