_Properties for_ `experiment`:

[horizontal]
`nReplicates`:: The number of times all elementary treatments must be replicated. Use this only if there is an internal source of variation in simulations, like random numbers. Otherwise all simulations will be strictly identical.

_Cross-links for_ `experiment`:

`baseLine -> system:<[underline]##__name__##>` {1}::
This link points to a model setup (<<configuration-reference.adoc#truethe-system-node>>) that will be used as a _base line_ simulation. A base line simulation is the equivalent of a control in a real experiment, i.e. a reference case that serves as a basis to which other treatments are compared. Often, the base line is the setup for which data is available to compare simulation outputs to.

===== Simulation duration

`/3worlds/experiment/*timePeriod*` {0..*}

The duration of a particular simulation is specified using a `timePeriod` node. 

*[TO DO: sort out the conflict between this and the stopping conditions]*

_Properties for_ `timePeriod`

[horizontal]
`start`:: The starting time of a simulation in `timeLine` shortest time units.
`end`::  The ending time of a simulation in `timeLine` shortest time units.

NOTE: Both properties are optional. If none is set, the simulation will start at time 0 and run indefinitely.

_Cross-links for_ `timePeriod`:

`stopOn -> stoppingCondition:<[underline]##__name__##>` {0..1}::
This link tells how to stop the simulation in case no `end` property is given.

NOTE: The stopping condition has the priority over the `end` property. 
** TO DO: check this**

===== Experimental design

`/3worlds/experiment/*design*:<[underline]##__name__##>` {1}

An experimental design specifies the method used to perform the simulations, e.g. number of replicate simulations, treatments as changes in parameter values or initial states, etc. An experimental design can be specified by using standard designs, or by passing a design description file.

For more information on experimental designs for simulation experiments, we recommend reading the documentation of the R software _planor_ and _mtk_ packages (e.g. these packages could be used to generate design files for use in 3Worlds).

**[TO DO: OpenMole integration]**

include::ArchetypeDoc-design.adoc[]

===== Experimental treatments

====== Treatments

`/3worlds/experiment/*treatment*:<[underline]##__name__##>` {0..*}

An experimental treatment records a particular set of parameter values and initial state to run a simulation or a series of replicated simulations. It is the basic block of the experiment, just as in real-world experimentation.

Treatements may be specified 

* in full detail: this is done by specifying more than one `system` nodes, each `system` being used for a different treatment;

* as (minor) changes relative to the experiment `baseLine`.

**NB: not fully implemented yet**

====== Treatments as changes relative to _baseLine_

`/3worlds/experiment/treatment/*modelChange*` {0..*}

**NB: not fully implemented yet**

===== Managing experiment data

====== Inputs: _dataSource_

`/3worlds/experiment/*dataSource*:<[underline]##__name__##>` {0..*}

This node describes a source of data to use to instantiate a model: name of the data source, access method, etc.

_Properties for_ `dataSource`

[horizontal]
`file`:: A valid data file name
`subclass`:: A data format to use to read that file
+
****
_possible values_:

[horizontal]
`CsvFileLoader`:: https://en.wikipedia.org/wiki/Comma-separated_values[comma separated value] `.csv` text file
`OdfFileLoader`:: https://en.wikipedia.org/wiki/OpenDocument[OpenDocument] `.ods` spreadsheet
****
`read`:: (optional) A list of the column headers to read. Each column name must match a declared `field` (<<configuration-dataDefinition.adoc#truefield>>) or `table` (<<configuration-dataDefinition.adoc#truetable>>). If this property is absent or not set, all columns will be read.
`idLifeCycle`:: (optional) Header of the column containing the _life cycle_ names (instances of <<configuration-ecosystem-structure.adoc#truelife-cycle,`lifeCycleType`>>). If only this property is set, each row of the file/spreadsheet will be used to generate a different _life cycle_ instance (with associated component container, constants, drivers and decorators). If it used in conjunction with `idGroup` and/or `idComponent` (see below), it will be used to search for or create the proper _life cycle_ container  in which to place the requested items (__groups__ or __components__). Values of this property will become the life cycle instance unique identifiers. They must be consistently used across `dataSource` / `initialValues` nodes when initial items are constructed from more than one source.
`idGroup`:: (optional) Header of the column containing the _group_ names (instances of <<configuration-ecosystem-structure.adoc#truecomponent-group,`groupType`>>). If only this property is set, each row of the file/spreadsheet will be used to generate a different _group_ instance (with associated component container, constants, drivers and decorators). If it used in conjunction with `idComponent` (see below), it will be used to search for or create the proper _group_ container  in which to place the requested __components__. Values of this property will become the group instance unique identifiers. They must be consistently used across `dataSource` / `initialValues` nodes when initial items are constructed from more than one source. If the `groupType` is declared as the child of a `lifeCycleType`, then the `idLifeCycle` property (cf. above) is also required, either in `dataSource` or `initialValues` nodes.
`idComponent`:: (optional) Header of the column containing system _component_ unique identifiers (instances of <<configuration-ecosystem-structure.adoc#truesystem-component,`componentType`>>). Every different value will generate a different __component__. Contrary to the two previous properties, the value is _not_ used to generate the component instance identifier, which is specifically generated by 3Worlds. Nevertheless, they must be consistently used across `dataSource` / `initialValues` nodes when initial items are constructed from more than one source. If the `componentType` is declared as the child of a `groupType`, then the `idGroup` property (cf. above) is also required, either in `dataSource` or `initialValues` nodes.
`dim`:: (optional) A list of column headers containing dimension indices. This must only be present when other column headers refer to tables. When this property is present, every column name must match a declared `table` <<configuration-dataDefinition.adoc#truetable,`table`>> with as many dimensions as listed here, and compatible maximal index values.

_Additional properties when_ `subclass = CsvFileLoader`

[horizontal]
`separator`:: the field separator used for this `.csv` file (default: tabulation `"\t"`)

_Additional properties when_ `subclass = OdfFileLoader`

[horizontal]
`sheet`:: the name of the spreadsheet to load from this `.ods` file (different spreadsheets in the same `.ods` file must be specified as different `dataSource` nodes). If this property is absent or not set, the first spreadsheet will be loaded.

_Additional properties when_ `subclass = CsvFileLoader`, `OdfFileLoader`

`.csv` and `.ods` file formats both assume the data come in 2 dimensional tables with cross-references between the tables. Table columns must match parameter and driver field or table names. Table rows must match species, stage or system component instances.

The following rules must be respected when preparing the data files:

* The data must not contain any missing value or structural empty cells.
* Empty lines are permitted (they are skipped).
* Text data must not be quoted.
* The first data line of any file or spreadsheet must contain column headers. They must match field names as defined under the `dataDefinition` node (<<configuration-reference.adoc#truethe-datadefinition-node>>).


====== Outputs: _dataSink_

`/3worlds/experiment/*dataSink*:<[underline]##__name__##>` {0..*}

This node describes a 'sink' where data resulting from simulation output is to be stored for later processing by other software.

*[Not yet implemented]*

_Properties for_ `dataSink`

[horizontal]
`file`:: A valid data file name

_Cross-links for_ `dataSink`:

`source -> dataTracker:<[underline]##__name__##>` {1}::
This link the origin of the data to save into the sink. Usually, a  <<configuration-ecosystem-dynamics.adoc#truedata-tracking,data tracker>>