Simulators usually rely on possibly large data sets to initialise and run a simulation. 

==== Data uses

According to their use during a simulation, we can classify data into:

[horizontal]
Parameters:: Values usually visible to a large number of system components that remain constant over a simulation or over the life time of an ephemeral component. These are stored in the <<truethe-systemstructure-node,constants>> of components, groups, life cycles and the arena. 
+
__Examples__: the _average solar radiation at the top of the canopy_ for the arena component; the _spatial coordinates_ of a plant; the _species name_ for a group of components.

Initial community:: In most cases a simulation must start with a non-empty initial system. This implies that components be instantiated with specific initial values for their <<truethe-systemstructure-node,drivers>> and proper connections between them.
+
__Examples__: an initial forest reconstructed from LIDAR data; a monitored population of marked animals within an area, where each animal has a measured age.

Forcing data:: Sometimes a simulation requires that data be fed in during its time course, at some time step, replacing values of a driver that cannot be computed by the model.
+
__Examples__: a series of metorological data used to force a fire spread or a vegetation growth model.

==== Data input methods

There are three different ways of feeding `ModelRunner` with data to start a simulation experiment (cf. <<truethe-setup-of-an-initial-state-for-a-simulation>> for the specification of these):

. Entering parameter and initial driver values in the model configuration tree. This is useful only for small quantities of data, with model requiring only a few parameters, or during the initial building/testing file of a model. Typically when one does not want to bother with formatting an input file with two parameter values. This is specified using `initialValues` nodes.
. Loading data from an external source, typically, one or more files. This is recommended whenever a large number of initial values and items must be used. This is specified using `loadFrom` cross-links to `dataSource` nodes (<<truethe-experiment-node>>).
. Using a user-defined initialiser function to set or modify initial values. This complements both points above and enables to compute transformations of initial drivers or constants prior to run the simulation. This is specified using the `SetInitialState` type (<<truefunction>>). 

These three methods can be used together within the same model. However, since an initialiser function must be run on an existing instance of a component, it can only be used (i) on the `system` node, which is always instantiated and unique, or (ii) as a complement to the two other methods which can specify the component instances to create.

Data for _parameters_ and _initial community_ are directly used to instantiate components and fill their descriptors with values. _Forcing data_ must be loaded into some initial data structure (probably most often a `DoubleTable`, cf. <<truetable>>, as a constant in the `system` instance), made accessible to some user-defined function that will read its content as simulation progresses.

==== Consistency of data files with the model component hierarchy

The simulated system is a hierarchy with up to 4 levels: arena > life cycle > group > component (cf. Box <<system-howto>>). As a consequence, input data files must reflect this hierarchy.


==== Data file formats

==== Import data from external sources


